script:
 - "test/sass-compile-check.sh"

before_install:
 - gem install sass
 - chmod +x test/sass-compile-check.sh

 deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: developer