script:
 - "build/sass-compile-check.sh"

language: sass
before_install:
 - gem install sass
 - chmod +x build/sass-compile-check.sh

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master